name: heatsafenet
channels: 
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - shapely
  - rtree
  - rasterio
  - rioxarray
  - xarray
  - osmnx
  - networkx
  - pyproj
  - numpy
  - pandas
  - or-tools
  - pulp
  - requests
  - tqdm
  - scikit-learn
  - matplotlib
  - seaborn
  - contextily
  - uvicorn
  - fastapi
  - folium
  - jinja2
  - black
  - isort
  - ruff
  - pytest
  - pip
  - pip:
      - google-api-python-client
      - earthengine-api